development:
  adapter: postgresql
  encoding: unicode
  database: city-rater_development
  pool: 5
  username: 
  password:
test:
  adapter: postgresql
  encoding: unicode
  database: city-rater_test
  pool: 5
  username:
  password:
